### ISSUE TITLE
Gifting no longer supported by Apple

### ISSUE THREAD

**Issue by individuate** [aporat/iTellAFriend#13]
Just a head's up that apparently gifting is no longer supported by Apple. 

A current app in the store is returning:

> Feature Not Supported
> This feature is no longer supported.

Instead, do something like:

```
NSString *iTunesLink = @"http://itunes.apple.com/us/app/APP_ID_HERE?mt=8";
[[UIApplication sharedApplication] openURL:[NSURL URLWithString:iTunesLink]]; 
```

I like the iTellAFriend module a lot, it's a shame Apple didn't provide a head's up that they broke this functionality.

**Comment by aporat** [comment]
agree. the gift feature has been removed
