### ISSUE TITLE
Localization & Improvements

### ISSUE THREAD

**Issue by moleksyuk** [aporat/iTellAFriend#5]
Hi @aporat,

I have some suggestions for your iTellAFriend library to make it more simpler and cleaner: 
1. Add Localization via iTellAFriend.bundle (like [iRate](https://github.com/nicklockwood/iRate) has it)
2. "Saw out" the 'Rate Application' functionality just because:<br>
   2.1. iTellAFriend was designed to share link to Application via mail, but now it's a car that can fly(Rate/Gift App) :smile: 
   2.1. iRate already includes your functionality<br>
   2.2. iRate has some extra staff<br>

P.S. I don't have any relations to iRate but I use both of these libs in my own project.
P.P.S. It's just IMHO, so if you are disagree you can close this ticket.

**Comment by aporat** [comment]
I'll check the localization issues. thanks.

I agree, this framework was initially designed only to display a "tell a friend" email view, but over time, some extra features were added . most of the features that were added are related to telling and sharing your app, so the project name is still somewhat okay :-)
