### ISSUE TITLE
Updated dismissModal

### ISSUE THREAD

**Issue by myacavone** [aporat/iTellAFriend#6]
Hi, 

I'm not yet up to speed on git pull requests, but I made a change you might want to incorporate. 

In iTellAFriend.m, line 241, I was getting a warning that "dismissModalViewControllerAnimated" is deprecated. I'm requiring iOS6+, so I changed line 241 to:

[controller dismissViewControllerAnimated:YES completion:nil];

A minor change, but I'm always trying to compile without warnings.

Thanks for a great module.

**Comment by aporat** [comment]
Hi. This framework was designed to work with iOS 5+, so using `dismissModalViewControllerAnimated` is required. 

if you want, you can change your project deployment version to 5.0 to hide this warning message.
