### ISSUE TITLE
Invalid sources in tag 1.3.0

### ISSUE THREAD

**Issue by moleksyuk** [aporat/iTellAFriend#7]
Hi @aporat 

I've started using cocoapods in my project and found issue with your iTellAFriend lib.

Your tag 1.3.0 doesn't include your fix for Issue #3 where self.applicationSellerName was removed.

So, having the latest 1.3.0 and not published my app yet I got false in method

``` objective-c
[[iTellAFriend sharedInstance] canTellAFriend]
```

because it looks in the latest tag as

``` objective-c
- (BOOL)canTellAFriend
{
    if ([MFMailComposeViewController canSendMail] &&self.applicationSellerName) {
        return true;
    }

    return false;

}
```

but has to

``` objective-c
- (BOOL)canTellAFriend
{
    if ([MFMailComposeViewController canSendMail]) {
        return true;
    }

    return false;

}
```

And BTW, comments at the header of sources still have 

``` objective-c
//
// Version 1.1.0
//
// Copyright 2011-2012 Kosher Penguin LLC
```

**Comment by aporat** [comment]
Thanks. I've added an updated spec to the cocoapods repository. you should be able to use 1.4.0 now.
