### ISSUE TITLE
iTellAFriend latest tag doesn't include the latest changes.

### ISSUE THREAD

**Issue by moleksyuk** [aporat/iTellAFriend#9]
Hi @aporat 
Could you upload 1.4.1 with all latest changes? (for example see my comment for pull request #8 )

**Comment by arturgrigor** [comment]
Hey @moleksyuk, you can use the following line in the Podfile and you'll have the latest changes
pod 'iTellAFriend', :podspec => 'https://raw.github.com/arturgrigor/iTellAFriend/master/iTellAFriend.podspec'

**Comment by aporat** [comment]
sorry about that! i've updated the podspec
